### ISSUE TITLE
Релиз мода для новой версии

### ISSUE THREAD

**Issue by ghost** [ArtFect/Smooth-Zoom#4]
Приветствую. Хотелось бы узнать, сможете ли Вы выпустить данный мод на более свежии версии майнкрафта? От 1.13 и выше

**Comment by ArtFect** [comment]
Вот есть более функциональный аналог на новые версии
https://www.curseforge.com/minecraft/mc-mods/ok-zoomer

**Comment by ghost** [comment]
Спасибо
